add suffix for getting different statefiles

diff --git a/.github/workflows/manage-eks-cluster.yml b/.github/workflows/manage-eks-cluster.yml
--- a/.github/workflows/manage-eks-cluster.yml
+++ b/.github/workflows/manage-eks-cluster.yml
@@ -5,6 +5,11 @@ on:
     branches:
       - main
   workflow_dispatch:
+    inputs:
+      action:
+        description: 'Terraform action to perform (apply or destroy)'
+        required: true
+        default: 'apply'
 
 jobs:
   manage_cluster:
@@ -49,15 +54,21 @@ jobs:
           echo "user: ${{ env.AWS_USER }}" >> secrets.txt
           cat secrets.txt
 
-        # Setup AWS CLI
+      # Setup AWS CLI
       - name: Configure AWS Credentials
         run: |
           env | grep -i aws
           aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
           aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
 
+      - name: Generate backend.hcl
+        run: |
+          SUFFIX=${GITHUB_ACTOR}
+          echo "key = \"workshop1-${SUFFIX}/terraform.tfstate\"" > backend.hcl
+          echo "Generated suffix: ${SUFFIX}"
+
       - name: Terraform Init
-        run: terraform init
+        run: terraform init -backend-config=backend.hcl
 
       - name: Terraform Format
         run: terraform fmt
@@ -65,6 +76,14 @@ jobs:
       - name: Terraform Validate
         run: terraform validate
 
-      - name: Terraform Apply
-        id: terraform_apply
-        run: terraform apply -auto-approve
+      - name: Terraform Apply or Destroy
+        id: terraform_action
+        run: |
+          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+            terraform apply -auto-approve
+          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+            terraform destroy -auto-approve
+          else
+            echo "Invalid action specified: ${{ github.event.inputs.action }}"
+            exit 1
+          fi
